[tool.poetry]
name = "post-spatializer-gpu"
version = "0.1.0"
description = "Spatialize posts using UMAP with GPU acceleration"
authors = ["Joshua Graph Team"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.0"
numpy = "^1.24.0"
cupy-cuda12x = "^12.3.0"  # Pour CUDA 12.x
cudf-cu12 = "^23.12"      # RAPIDS cuDF pour CUDA 12
cuml-cu12 = "^23.12"      # RAPIDS cuML pour CUDA 12
tqdm = "^4.66.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 